### PR TITLE
queryx: Added CAS exec functions (#98)

### LINKED ISSUE #98: Support for CAS Operation Insight (LWT)
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useInsertLWT.html

I'm using the gocqlx library and performing a conditional update with the query builder. I'm not seeing an obvious way to determine whether a query was applied vs experiencing an error.

In plain gocql library, functions like https://godoc.org/github.com/gocql/gocql#Query.MapScanCAS return an applied bool to check whether the update was successful.

I don't see any similar return for Exec() or ExecRelease() using gocqlx. https://godoc.org/github.com/scylladb/gocqlx#Queryx.Exec Do these functions return an error when the update fails to apply based on the IF conditional?

Here's how I'm using this today: https://play.golang.org/p/WfnIAOzwZtC 

But, I've had instances where it seems the update has failed to apply, but returned cleanly and allowed the rest of my code to execute. I'm using this in a job locking mechanism and I've had the same job run twice on different workers.

### PR DESCRIPTION
**Pull request by zimnx**
Added ExecCAS and ExecCASRelease functions suitable for INSERT ... IF
NOT EXISTS and UPDATE's containing IF statement.
Functions returns information wheter query was applied or not.

Fixes #98

### CODE REVIEW

File: example_test.go [hunk 1]
```diff
@@ -201,11 +207,54 @@ CREATE TABLE IF NOT EXISTS gocqlx_test.person (
...
+			[]string{"stephen.johns@gocqlx_test.com"},
+			500,
+		}
+
+		stmt, names := qb.Insert("gocqlx_test.person").
+			Columns("first_name", "last_name", "email", "salary").
+			Unique().
+			ToCql()
+
+		applied, err := session.Query(stmt, names).BindStruct(p).ExecCASRelease()
```
Comment (mmatczuk) [inline example_test.go:234]: Exec?

File: example_test.go [hunk 2]
```diff
@@ -201,11 +207,54 @@ CREATE TABLE IF NOT EXISTS gocqlx_test.person (
...
+		if err != nil {
+			t.Fatal(err)
+		}
+
+		t.Log(applied)
+
+		stmt, names = qb.Update("gocqlx_test.person").
+			SetNamed("salary", "new_salary").
+			If(qb.Lt("salary")).
```
Comment (mmatczuk) [inline example_test.go:243]: If goes after where

File: example_test.go [hunk 3]
```diff
@@ -201,11 +207,54 @@ CREATE TABLE IF NOT EXISTS gocqlx_test.person (
...
+			Where(qb.Eq("first_name"), qb.Eq("last_name")).
+			ToCql()
+		q := session.Query(stmt, names).BindMap(qb.M{
```
Comment (mmatczuk) [inline example_test.go:246]: I'd suggest to use BindStructMap here

File: iterx.go [hunk 4]
```diff
@@ -257,27 +258,39 @@ func (iter *Iterx) structScan(value reflect.Value) bool {
 		panic("value must be a pointer")
 	}
 
+	casResponse := false
 	if iter.fields == nil {
 		columns := columnNames(iter.Iter.Columns())
-		iter.fields = iter.Mapper.TraversalsByName(value.Type(), columns)
+		if len(columns) > 0 && columns[0] == "[applied]" {
```
Comment (mmatczuk) [inline iterx.go:264]: "[applied]" should be a const

File: iterx.go [hunk 5]
```diff
@@ -257,27 +258,39 @@ func (iter *Iterx) structScan(value reflect.Value) bool {
...
+		iter.fields = iter.Mapper.TraversalsByName(value.Type(), columns)
 		// if we are not unsafe and are missing fields, return an error
 		if !iter.unsafe {
 			if f, err := missingFields(iter.fields); err != nil {
 				iter.err = fmt.Errorf("missing destination name %q in %s", columns[f], reflect.Indirect(value).Type())
 				return false
 			}
 		}
-		iter.values = make([]interface{}, len(columns))
+		iter.values = make([]interface{}, len(columns), cap(columns))
```
Comment (mmatczuk) [inline iterx.go:278]: Why?

File: iterx.go [hunk 6]
```diff
@@ -257,27 +258,39 @@ func (iter *Iterx) structScan(value reflect.Value) bool {
 		panic("value must be a pointer")
 	}
 
+	casResponse := false
```
Comment (mmatczuk) [inline iterx.go:261]: This only work for the 1st row!

It would be better to prepend `iter.fields` with nil to accomodate for applied and and init iter.values[0] in the if branch below.

Comment (mmatczuk) [reply iterx.go:261]: I'd rename that to just cas btw.

File: queryx.go [hunk 7]
```diff
@@ -209,6 +209,23 @@ func (q *Queryx) ExecRelease() error {
 	return q.Exec()
 }
 
+// ExecCAS executes the Lightweight Transaction query, returns whether query was applied.
+// It's suitable for INSERT ... IF NOT EXISTS and UPDATE's having IF conditions.
```
Comment (mmatczuk) [inline queryx.go:213]: A link to Scylla docs on LWT would be more correct.

File: queryx.go [hunk 8]
```diff
@@ -236,6 +253,29 @@ func (q *Queryx) GetRelease(dest interface{}) error {
 	return q.Get(dest)
 }
 
+// GetCAS executes a lightweight transaction (i.e. an UPDATE or INSERT
```
Comment (mmatczuk) [inline queryx.go:256]: Again add LWD docs link and let's not get into too many details.

File: queryx.go [hunk 9]
```diff
@@ -236,6 +253,29 @@ func (q *Queryx) GetRelease(dest interface{}) error {
...
+// statement containing an IF clause). If the transaction fails because
+// the existing values did not match, the previous values will be stored
+// in dest object.
+//
+// As for INSERT .. IF NOT EXISTS, previous values will be returned as if
+// SELECT * FROM.
```
Comment (mmatczuk) [inline queryx.go:262]: with "SELECT * FROM ..." query

**Comment by mmatczuk** [comment]
Thanks!
